//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreNet.CodeStandard.NamingRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoreNet.CodeStandard.NamingRules.NamingResources", typeof(NamingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method should end with &quot;Async&quot;.
        /// </summary>
        internal static string MN1300Description {
            get {
                return ResourceManager.GetString("MN1300Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method &apos;{0}&apos; should renamed to &apos;{0}Async&apos;.
        /// </summary>
        internal static string MN1300MessageFormat {
            get {
                return ResourceManager.GetString("MN1300MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method should end with &quot;Async&quot;.
        /// </summary>
        internal static string MN1300Title {
            get {
                return ResourceManager.GetString("MN1300Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-async method must not end with &quot;Async&quot;.
        /// </summary>
        internal static string MN1301Description {
            get {
                return ResourceManager.GetString("MN1301Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailing &quot;Async&quot; of method &apos;{0}&apos; must be removed..
        /// </summary>
        internal static string MN1301MessageFormat {
            get {
                return ResourceManager.GetString("MN1301MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-async method must not end with &quot;Async&quot;.
        /// </summary>
        internal static string MN1301Title {
            get {
                return ResourceManager.GetString("MN1301Title", resourceCulture);
            }
        }
    }
}
